"""products inventory reports retraining

Revision ID: 20b7de432cbd
Revises: ae718c4f8aa4
Create Date: 2026-07-15 22:24:14.433100

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b7de432cbd'
down_revision: str | None = 'ae718c4f8aa4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_stock',
    sa.Column('clasificador', sa.String(length=64), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('clasificador', name=op.f('pk_inventory_stock'))
    )
    op.create_table('products',
    sa.Column('clasificador', sa.String(length=64), nullable=False),
    sa.Column('nombre_display', sa.String(length=255), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('costo_reposicion', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('clasificador', name=op.f('pk_products'))
    )
    op.create_table('report_generation_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('horizonte', sa.String(length=16), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('total_alertas', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_generation_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_generation_logs'))
    )
    op.create_index(op.f('ix_report_generation_logs_created_at'), 'report_generation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_generation_logs_user_id'), 'report_generation_logs', ['user_id'], unique=False)
    op.create_table('retraining_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', name='retraining_job_status'), nullable=False),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_retraining_jobs_triggered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retraining_jobs'))
    )
    op.create_index(op.f('ix_retraining_jobs_created_at'), 'retraining_jobs', ['created_at'], unique=False)
    op.add_column('sales_history', sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sales_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_history', 'updated_at')
    op.drop_column('sales_history', 'ingested_at')
    op.drop_index(op.f('ix_retraining_jobs_created_at'), table_name='retraining_jobs')
    op.drop_table('retraining_jobs')
    op.drop_index(op.f('ix_report_generation_logs_user_id'), table_name='report_generation_logs')
    op.drop_index(op.f('ix_report_generation_logs_created_at'), table_name='report_generation_logs')
    op.drop_table('report_generation_logs')
    op.drop_table('products')
    op.drop_table('inventory_stock')
    # ### end Alembic commands ###
