"""initial schema

Revision ID: ae718c4f8aa4
Revises: 
Create Date: 2026-07-15 14:44:04.590565

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae718c4f8aa4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clasificador', sa.String(length=64), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('cantidad_vendida', sa.Float(), nullable=False),
    sa.Column('precio_medio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_history')),
    sa.UniqueConstraint('clasificador', 'dia', name='uq_sales_history_clasificador_dia')
    )
    op.create_index(op.f('ix_sales_history_clasificador'), 'sales_history', ['clasificador'], unique=False)
    op.create_index(op.f('ix_sales_history_dia'), 'sales_history', ['dia'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('inference_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('clasificador', sa.String(length=64), nullable=False),
    sa.Column('fecha_objetivo', sa.Date(), nullable=False),
    sa.Column('horizonte', sa.Enum('day', 'week', 'range', name='prediction_horizon'), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('prediction_value', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inference_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inference_logs'))
    )
    op.create_index(op.f('ix_inference_logs_clasificador'), 'inference_logs', ['clasificador'], unique=False)
    op.create_index(op.f('ix_inference_logs_created_at'), 'inference_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_logs_user_id'), 'inference_logs', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id_revoked', 'refresh_tokens', ['user_id', 'revoked'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_request_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_logs'))
    )
    op.create_index(op.f('ix_request_logs_created_at'), 'request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_user_id'), 'request_logs', ['user_id'], unique=False)
    op.create_table('pipeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inference_log_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('started', 'completed', 'failed', name='pipeline_event_status'), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inference_log_id'], ['inference_logs.id'], name=op.f('fk_pipeline_events_inference_log_id_inference_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_events'))
    )
    op.create_index(op.f('ix_pipeline_events_inference_log_id'), 'pipeline_events', ['inference_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_events_inference_log_id'), table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_index(op.f('ix_request_logs_user_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_created_at'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index('ix_refresh_tokens_user_id_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_inference_logs_user_id'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_created_at'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_clasificador'), table_name='inference_logs')
    op.drop_table('inference_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sales_history_dia'), table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_clasificador'), table_name='sales_history')
    op.drop_table('sales_history')
    # ### end Alembic commands ###
